# Generated by Django 4.1.3 on 2022-12-12 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_answer', '0002_cardgroup_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='user',
            new_name='owner',
        ),
    ]
