# Generated by Django 4.1.3 on 2022-12-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_answer', '0004_alter_card_owner_alter_cardgroup_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='correct_answer',
            field=models.IntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D')], default=0),
        ),
    ]
